In [ ]:
Indexing and Slicing

In [3]:
import numpy as np

In [5]:
arr = np.arange(13,30)

print("Array: ",arr)

Array:  [13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [6]:
print ('Element at 7th index is : ', arr[7])

Element at 7th index is :  20


In [8]:
print ("Element at index 2nd, 4th and 9th is ", arr[[2,4,9]]) #Pass a list as index to subset

Element at index 2nd, 4th and 9th is  [15 17 22]


In [9]:
my_mat = [1,2,3] , [4,5,6] , [7,8,9]

mat = np.array(my_mat)

mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
print("\nDouble break indexing\n----------")
print("Element in row index 1 and column 2: ", mat[1][2])


Double break indexing
----------
Element in row index 1 and column 2:  6


In [11]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
print("Entire row at index 2: ", mat[2])
print("\nEntire column at index:\n ", mat[:,1:])

Entire row at index 2:  [7 8 9]
 
Entire column at index:
  [[2 3]
 [5 6]
 [8 9]]


In [23]:
print("\nSubsetting sub matrices\n---------------")
print("Matrix with row indices 1 and 2 and column indices 3 and 4\n", mat[1:2,1:2])


Subsetting sub matrices
---------------
Matrix with row indices 1 and 2 and column indices 3 and 4
 [[5]]


In [24]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
print("",mat[0:2,1:2])

 [[2]
 [5]]


In [ ]:
Update Matrix

In [34]:
print ("Original Matrix \n\n",mat)

Original Matrix 

 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [35]:
mat[0,1]=35
print(mat)

[[ 1 35  3]
 [ 4  5  6]
 [ 7  8  9]]


In [36]:
mat[2,2]=10
print(mat)

[[ 1 35  3]
 [ 4  5  6]
 [ 7  8 10]]


In [40]:
mat[0,0:3]=10

In [41]:
print(mat)

[[10 10 10]
 [25 25 25]
 [ 7  8 10]]


In [42]:
mat [1,:] = 25 
print(mat)

[[10 10 10]
 [25 25 25]
 [ 7  8 10]]


In [ ]:
Subseting

In [43]:
from numpy.random import randint as ri

In [49]:
mat = np.array(ri(10,100,15)).reshape(3,5)

In [52]:
print("Matrix of two digit numbers--------\n\n", mat)

Matrix of two digit numbers--------

 [[38 43 97 94 82]
 [78 49 79 48 28]
 [82 99 65 23 36]]


In [53]:
mat>50

array([[False, False,  True,  True,  True],
       [ True, False,  True, False, False],
       [ True,  True,  True, False, False]])

In [55]:
print ("Marks higher than 50--------\n", mat[mat>50])

Marks higher than 50--------
 [97 94 82 78 79 82 99 65]


In [56]:
# you can also use np.where to return some data based on condition

marks = 70
np.where(marks>68, "Pass","Fail")

array('Pass', dtype='<U4')

In [59]:
# Check non zeros

non_zero = ri(0,50,100)

print(non_zero)

np.count_nonzero(non_zero)

[25 16 36 25  0  9 18 19 43  7 46 14 19 40  4 26 35 20 34 21  9 17 47 25
 42 41 37  0 10 21 18 39 17 37 38  5 18 17  2 44 16 17 38 42 46 37 40 43
 10 26 46  0 18  1 48 39 17 10 30 15 30 17 42 27 39 22  6 46  3  8 19  5
 38 40 16 36  4 10  0  0 31 47 16 27  3 44 40 38 17 36  2 24  3 13 28 45
  0 49 30 18]


94

In [62]:
# Ravel or Flatten (this concept is used in deep learning for image processing)
array = ri (0, 20, size = (3,4))
print (array)

array.ravel()

[[19  4  4 11]
 [11  6  4  3]
 [14 15  0 12]]


array([19,  4,  4, 11, 11,  6,  4,  3, 14, 15,  0, 12])

In [64]:
#or flatten is the same
array.flatten()

array([19,  4,  4, 11, 11,  6,  4,  3, 14, 15,  0, 12])

In [ ]:
Universal functions

In [66]:
mat1 = np.array(ri(1,10,9)). reshape(3,3)

mat2 = np.array(ri(1,10,9)). reshape(3,3)

print("\n1st matrix of random single digit number\n----------\n", mat1)
print("\n2nd matrix of random single digit number\n----------\n", mat2)


1st matrix of random single digit number
----------
 [[8 8 1]
 [5 5 6]
 [5 9 3]]

2nd matrix of random single digit number
----------
 [[8 2 8]
 [1 5 9]
 [6 4 7]]


In [67]:
print("\nAddition\n-----------\n",mat1+mat2)


Addition
-----------
 [[16 10  9]
 [ 6 10 15]
 [11 13 10]]


In [68]:
print("\nMultiplication\n------\n", mat1*mat2)


Multiplication
------
 [[64 16  8]
 [ 5 25 54]
 [30 36 21]]


In [ ]:
Broadcasting

In [70]:
start = np.zeros((3,3))
print (start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [71]:
add_rows = np.array([1,0,2])
print(add_rows)

[1 0 2]


In [75]:
y = start + add_rows #add to each row of start using broadcasting
print(y)

array([[1., 0., 2.],
       [1., 0., 2.],
       [1., 0., 2.]])

In [76]:
new_row=add_rows.T
new_row

array([1, 0, 2])

In [78]:
test = start + new_row
print (test)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]
